version: '1.0'
name: pipeline-20220703
displayName: pipeline-20220703
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-5dbef180
    displayName: '编译-打包'
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@golang
        name: build_golang
        displayName: Golang 构建
        golangVersion: '1.18'
        commands:
          - mkdir output
          - go env -w GO111MODULE=on
          - go env -w GOPROXY=https://goproxy.cn,direct
          - GOOS=linux GOARCH=amd64 go build -o output/ginskeleton-api.linux64 -ldflags "-w  -s"  -trimpath   ./cmd/api/main.go
          - chmod +X output/ginskeleton-api.linux64
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./output
        caches:
          - /go/pkg/mod
        strategy:
          retry: '0'
permissions:
  - role: admin
    members: []
